track_inputs:
  - d0
  - z0SinTheta
  - dphi
  - deta
  - qOverP
  - IP3D_signed_d0_significance
  - IP3D_signed_z0_significance
  - phiUncertainty
  - thetaUncertainty
  - qOverPUncertainty
  - numberOfPixelHits
  - numberOfSCTHits
  - numberOfInnermostPixelLayerHits
  - numberOfNextToInnermostPixelLayerHits
  - numberOfInnermostPixelLayerSharedHits
  - numberOfInnermostPixelLayerSplitHits
  - numberOfPixelSharedHits
  - numberOfPixelSplitHits
  - numberOfSCTSharedHits
  - ftagTruthOriginLabel
  - ftagTruthVertexIndex
 
jet_inputs:
  - pt_btagJes
  - eta_btagJes
  # - d0
  # - z0SinTheta
  # - dphi
  # - deta
  # - qOverP
  # - IP3D_signed_d0_significance 
  # - IP3D_signed_z0_significance
  # - phiUncertainty
  # - thetaUncertainty
  # - qOverPUncertainty 
  # - numberOfPixelHits
  # - numberOfSCTHits
  # - numberOfInnermostPixelLayerHits
  # - numberOfNextToInnermostPixelLayerHits 
  # - numberOfInnermostPixelLayerSharedHits
  # - numberOfInnermostPixelLayerSplitHits
  # - numberOfPixelSharedHits 
  # - numberOfPixelSplitHits
  # - numberOfSCTSharedHits
  # - numberOfPixelHoles
  # - numberOfSCTHoles
  # - pt


edge_features:
  - ftagTruthOriginLabel
  - ftagTruthVertexIndex
  - truthParentBarcode

vertex_features:
  pt:
    log: True
  # eta:
  #   log: False

vertex_flavours:
  - "b"
  - "c"

flavour:
  b: 5
  c: 4
  light: None

ftagTruthOriginLabel:
  b: [3,4]
  c: [5,4]
  light: 2

HadronConeExclLabel:
  b: [5, 54, 55]
  c: [44, 4]
  light: 0
