inputs: 
  ttbar: /home/users/s/schroeer/scratch/PhD/Dataset_Dumper/samples/ttbar_410470_20220428_fixed_taus

output: /home/users/s/schroeer/scratch/PhD/Output

edge_feature_network:
  nodes: [70,70,70,30]
  n_tracks_name: tracks

edge_weight_network:
  nodes: [70,70,70,1]
  n_tracks_name: tracks

vertex_network:
  nodes: [50,50,50,18]
